Update smp-pzpi-23-5-tokhtamysh-mariia-lab1-code

diff --git a/Lab1/smp-pzpi-23-5-tokhtamysh-mariia-lab1/smp-pzpi-23-5-tokhtamysh-mariia-lab1-code b/Lab1/smp-pzpi-23-5-tokhtamysh-mariia-lab1/smp-pzpi-23-5-tokhtamysh-mariia-lab1-code
--- a/Lab1/smp-pzpi-23-5-tokhtamysh-mariia-lab1/smp-pzpi-23-5-tokhtamysh-mariia-lab1-code
+++ b/Lab1/smp-pzpi-23-5-tokhtamysh-mariia-lab1/smp-pzpi-23-5-tokhtamysh-mariia-lab1-code
@@ -1,4 +1,5 @@
 #!/bin/bash
+script_dir="$(cd "$(dirname "$0")" && pwd)"
 
 convert_encoding() {
   local enc_src="WINDOWS-1251"
@@ -61,8 +62,8 @@ generate_output_csv() {
   }
   NR > 1 {
       for(i = 1; i <= NF; i++) {
-          sub(/^\"/, "", $i)
-          sub(/\"$/, "", $i)
+          sub(/^"/, "", $i)
+          sub(/"$/, "", $i)
       }
       if ($1 ~ "^" group " -") {
           subject = $12
@@ -104,24 +105,28 @@ generate_output_csv() {
   echo "File $OUTPUT_FILE created!"
 }
 
+is_schedule_file() {
+  local f="$1"
+  [[ "$f" =~ ^TimeTable_[0-9]{2}_[0-9]{2}_[0-9]{4}\.csv$ ]] && return 0 || return 1
+}
 
 main() {
   script_dir="$(cd "$(dirname "$0")" && pwd)"
 
-  if [[ -n "$1" && -n "$2" ]]; then
-    selected_group="$1"
+  if [[ -n "$2" ]]; then
     selected_file="$2"
     [[ "$selected_file" != /* ]] && selected_file="$script_dir/$selected_file"
-  else
-    if [ -z "$1" ] || [[ "$1" =~ - ]]; then
-      select_timetable_file
-    else
-      selected_file="$1"
-      shift
-    fi
-  fi
 
-  [[ "$selected_file" != /* ]] && selected_file="$script_dir/$selected_file"
+  elif [[ -n "$1" ]]; then
+    if is_schedule_file "$1" && [[ -f "$script_dir/$1" ]]; then
+      selected_file="$script_dir/$1"
+    else
+      select_timetable_file
+    fi
+
+  else
+    select_timetable_file
+  fi
 
   if [[ ! -f "$selected_file" ]]; then
     echo "Error: File '$selected_file' not found!"
@@ -136,6 +141,7 @@ main() {
   extract_groups || { echo "No valid groups found!"; exit 1; }
 
   groups=$(cat .group_list)
+
   echo "Found groups in the file:"
   echo "$groups"
 
@@ -144,13 +150,18 @@ main() {
     exit 1
   fi
 
-  if [[ -z "$selected_group" ]]; then
-    select_group
-  else
-    if ! grep -q "$selected_group" <<< "$groups"; then
-      echo "Error: Group '$selected_group' not found in the file!"
-      exit 1
+  if [[ -n "$1" ]]; then
+    if ! is_schedule_file "$1"; then
+      selected_group="$1"
+      if ! grep -qxF "$selected_group" <<< "$groups"; then
+        echo "Error: Group '$selected_group' not found in the file!"
+        exit 1
+      fi
+    else
+      select_group
     fi
+  else
+    select_group
   fi
 
   OUTPUT_FILE="$script_dir/Google_$(basename "$selected_file")"
